### ISSUE TITLE
Plugin throws exception in Grails 3.0.4

### ISSUE THREAD

**Issue by ManvendraSK** [sheehan/grails-console#40]
I crossed check this plugin with Grails 3.0.2's vanilla app and it's working fine, but has some issue with Grails 3.0.4's vanilla app. Here is the dependency that I used in `build.gradle` file and the associated stacktrace occurring while visiting `/console` url.
```groovy 
dependencies {
   runtime 'org.grails.plugins:grails-console:2.0.2'
}
```

*stacktrace:*

> ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/console/index.gsp:9] Error executing tag <g:render>: No such property: AssetPipelineConfigHolder for class: asset.pipeline.grails.CachingLinkGenerator] with root cause
groovy.lang.MissingPropertyException: No such property: AssetPipelineConfigHolder for class: asset.pipeline.grails.CachingLinkGenerator
        at asset.pipeline.grails.CachingLinkGenerator.asset(CachingLinkGenerator.groovy:32) ~[asset-pipeline-3.0.5.jar:na]
        at asset.pipeline.grails.CachingLinkGenerator.resource(CachingLinkGenerator.groovy:18) ~[asset-pipeline-3.0.5.jar:na]
        at gsp_grails_console_console_favicon_gsp.run(gsp_grails_console_console_favicon_gsp.groovy:15) ~[grails-console-2.0.2.jar:na]
        at gsp_grails_console_consoleindex_gsp$_run_closure1.doCall(gsp_grails_console_consoleindex_gsp.groovy:27) ~[grails-console-2.0.2.jar:na]
        at gsp_grails_console_consoleindex_gsp.run(gsp_grails_console_consoleindex_gsp.groovy:34) ~[grails-console-2.0.2.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_51]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]

**Comment by sheehan** [comment]
This is caused by an error in the asset-pipeline plugin v3.0.5. It works if you upgrade asset-pipeline to the latest (3.0.7) in build.gradle. I'll add a note to the readme.

**Comment by ManvendraSK** [comment]
Thanks mate. It worked like charm. Thanks for quick response. I guess Grails generation system should now generate asset-pipeline dependency with v3.0.5. Am I right?
